# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QMainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QProgressBar, QPushButton, QSizePolicy, QSpacerItem,
    QTabWidget, QTextBrowser, QTextEdit, QVBoxLayout,
    QWidget)
from codingQrc import IconRc

class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        if not QMainWindow.objectName():
            QMainWindow.setObjectName(u"QMainWindow")
        QMainWindow.setEnabled(True)
        QMainWindow.resize(760, 800)
        QMainWindow.setMinimumSize(QSize(760, 800))
        icon = QIcon()
        icon.addFile(u":/logo/resources/toolboxs.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        QMainWindow.setWindowIcon(icon)
        self.QMainWidget = QWidget(QMainWindow)
        self.QMainWidget.setObjectName(u"QMainWidget")
        self.horizontalLayout = QHBoxLayout(self.QMainWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Left = QVBoxLayout()
        self.Left.setObjectName(u"Left")
        self.Left.setContentsMargins(-1, -1, -1, 30)
        self.LeftWidget = QWidget(self.QMainWidget)
        self.LeftWidget.setObjectName(u"LeftWidget")
        self.LeftWidget.setMinimumSize(QSize(90, 630))
        self.LeftWidget.setMaximumSize(QSize(90, 16777215))
        self.LeftWidget.setStyleSheet(u"background-color: #f9f9f9")
        self.verticalLayout = QVBoxLayout(self.LeftWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.OpenButton = QPushButton(self.LeftWidget)
        self.OpenButton.setObjectName(u"OpenButton")
        self.OpenButton.setMinimumSize(QSize(0, 55))
        self.OpenButton.setStyleSheet(u"QPushButton\n"
"{\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#b3d7f3;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#80bceb;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u":/logo/resources/fileopen.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.OpenButton.setIcon(icon1)
        self.OpenButton.setIconSize(QSize(45, 45))
        self.OpenButton.setFlat(True)

        self.verticalLayout.addWidget(self.OpenButton)

        self.OpenLabel = QLabel(self.LeftWidget)
        self.OpenLabel.setObjectName(u"OpenLabel")
        font = QFont()
        font.setPointSize(8)
        self.OpenLabel.setFont(font)
        self.OpenLabel.setStyleSheet(u"background-color: #f9f9f9")
        self.OpenLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.OpenLabel)

        self.CleanButton = QPushButton(self.LeftWidget)
        self.CleanButton.setObjectName(u"CleanButton")
        self.CleanButton.setMinimumSize(QSize(0, 55))
        self.CleanButton.setStyleSheet(u"QPushButton\n"
"{\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#b3d7f3;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#80bceb;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"}")
        icon2 = QIcon()
        icon2.addFile(u":/logo/resources/clear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.CleanButton.setIcon(icon2)
        self.CleanButton.setIconSize(QSize(45, 45))
        self.CleanButton.setFlat(True)

        self.verticalLayout.addWidget(self.CleanButton)

        self.CleanLabel = QLabel(self.LeftWidget)
        self.CleanLabel.setObjectName(u"CleanLabel")
        self.CleanLabel.setFont(font)
        self.CleanLabel.setStyleSheet(u"background-color: #f9f9f9")
        self.CleanLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.CleanLabel)

        self.ShowButton = QPushButton(self.LeftWidget)
        self.ShowButton.setObjectName(u"ShowButton")
        self.ShowButton.setMinimumSize(QSize(0, 55))
        self.ShowButton.setStyleSheet(u"QPushButton\n"
"{\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#b3d7f3;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#80bceb;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"}")
        icon3 = QIcon()
        icon3.addFile(u":/logo/resources/detail.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.ShowButton.setIcon(icon3)
        self.ShowButton.setIconSize(QSize(45, 45))
        self.ShowButton.setFlat(True)

        self.verticalLayout.addWidget(self.ShowButton)

        self.ShowLabel = QLabel(self.LeftWidget)
        self.ShowLabel.setObjectName(u"ShowLabel")
        self.ShowLabel.setFont(font)
        self.ShowLabel.setStyleSheet(u"background-color: #f9f9f9")
        self.ShowLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.ShowLabel)

        self.RegisterButton = QPushButton(self.LeftWidget)
        self.RegisterButton.setObjectName(u"RegisterButton")
        self.RegisterButton.setMinimumSize(QSize(0, 55))
        self.RegisterButton.setStyleSheet(u"QPushButton\n"
"{\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#b3d7f3;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#80bceb;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"}")
        icon4 = QIcon()
        icon4.addFile(u":/logo/resources/register.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.RegisterButton.setIcon(icon4)
        self.RegisterButton.setIconSize(QSize(45, 45))
        self.RegisterButton.setFlat(True)

        self.verticalLayout.addWidget(self.RegisterButton)

        self.RegisterLabel = QLabel(self.LeftWidget)
        self.RegisterLabel.setObjectName(u"RegisterLabel")
        self.RegisterLabel.setFont(font)
        self.RegisterLabel.setStyleSheet(u"background-color: #f9f9f9")
        self.RegisterLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.RegisterLabel)

        self.LogoutButton = QPushButton(self.LeftWidget)
        self.LogoutButton.setObjectName(u"LogoutButton")
        self.LogoutButton.setMinimumSize(QSize(0, 55))
        self.LogoutButton.setStyleSheet(u"QPushButton\n"
"{\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#b3d7f3;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#80bceb;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"}")
        icon5 = QIcon()
        icon5.addFile(u":/logo/resources/logout.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.LogoutButton.setIcon(icon5)
        self.LogoutButton.setIconSize(QSize(45, 45))
        self.LogoutButton.setFlat(True)

        self.verticalLayout.addWidget(self.LogoutButton)

        self.LogoutLabel = QLabel(self.LeftWidget)
        self.LogoutLabel.setObjectName(u"LogoutLabel")
        self.LogoutLabel.setFont(font)
        self.LogoutLabel.setStyleSheet(u"background-color: #f9f9f9")
        self.LogoutLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.LogoutLabel)

        self.LeftSpacer = QSpacerItem(0, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.LeftSpacer)


        self.Left.addWidget(self.LeftWidget)


        self.horizontalLayout.addLayout(self.Left)

        self.LeftLeft = QVBoxLayout()
        self.LeftLeft.setObjectName(u"LeftLeft")
        self.LeftLeft.setContentsMargins(-1, -1, -1, 30)
        self.ListBrowser = QTextBrowser(self.QMainWidget)
        self.ListBrowser.setObjectName(u"ListBrowser")
        self.ListBrowser.setStyleSheet(u"QTextEdit { background-color: #f9f9f9; border: unset; }")
        self.ListBrowser.setReadOnly(False)

        self.LeftLeft.addWidget(self.ListBrowser)


        self.horizontalLayout.addLayout(self.LeftLeft)

        self.Right = QVBoxLayout()
        self.Right.setObjectName(u"Right")
        self.TabWidget = QTabWidget(self.QMainWidget)
        self.TabWidget.setObjectName(u"TabWidget")
        self.TabWidget.setMinimumSize(QSize(510, 321))
        self.TabWidget.setMaximumSize(QSize(510, 321))
        self.Tab01 = QWidget()
        self.Tab01.setObjectName(u"Tab01")
        self.ModeFrame01 = QFrame(self.Tab01)
        self.ModeFrame01.setObjectName(u"ModeFrame01")
        self.ModeFrame01.setGeometry(QRect(10, 10, 191, 61))
        self.ModeFrame01.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ModeFrame01.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame01.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModeFrame01.setLineWidth(1)
        self.ModeFrame01.setMidLineWidth(0)
        self.LockCheckBox01 = QCheckBox(self.ModeFrame01)
        self.LockCheckBox01.setObjectName(u"LockCheckBox01")
        self.LockCheckBox01.setGeometry(QRect(130, 20, 51, 21))
        font1 = QFont()
        font1.setPointSize(10)
        self.LockCheckBox01.setFont(font1)
        self.LockCheckBox01.setChecked(True)
        self.ComboBox01 = QComboBox(self.ModeFrame01)
        self.ComboBox01.addItem("")
        self.ComboBox01.addItem("")
        self.ComboBox01.setObjectName(u"ComboBox01")
        self.ComboBox01.setEnabled(False)
        self.ComboBox01.setGeometry(QRect(20, 20, 91, 22))
        self.Label05 = QLabel(self.Tab01)
        self.Label05.setObjectName(u"Label05")
        self.Label05.setGeometry(QRect(20, 0, 35, 20))
        self.Label05.setStyleSheet(u"background-color: #ffffff;")
        self.Label05.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame02 = QFrame(self.Tab01)
        self.ModeFrame02.setObjectName(u"ModeFrame02")
        self.ModeFrame02.setGeometry(QRect(10, 90, 191, 61))
        self.ModeFrame02.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ModeFrame02.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame02.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModeFrame02.setLineWidth(1)
        self.ModeFrame02.setMidLineWidth(0)
        self.LockCheckBox02 = QCheckBox(self.ModeFrame02)
        self.LockCheckBox02.setObjectName(u"LockCheckBox02")
        self.LockCheckBox02.setGeometry(QRect(130, 20, 51, 21))
        self.LockCheckBox02.setFont(font1)
        self.LockCheckBox02.setChecked(True)
        self.ComboBox02 = QComboBox(self.ModeFrame02)
        self.ComboBox02.addItem("")
        self.ComboBox02.addItem("")
        self.ComboBox02.setObjectName(u"ComboBox02")
        self.ComboBox02.setEnabled(False)
        self.ComboBox02.setGeometry(QRect(20, 20, 91, 22))
        self.Label06 = QLabel(self.Tab01)
        self.Label06.setObjectName(u"Label06")
        self.Label06.setGeometry(QRect(20, 80, 35, 20))
        self.Label06.setStyleSheet(u"background-color: #ffffff;")
        self.Label06.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame04 = QFrame(self.Tab01)
        self.ModeFrame04.setObjectName(u"ModeFrame04")
        self.ModeFrame04.setGeometry(QRect(220, 10, 271, 91))
        self.ModeFrame04.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame04.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditIP01 = QLineEdit(self.ModeFrame04)
        self.LineEditIP01.setObjectName(u"LineEditIP01")
        self.LineEditIP01.setGeometry(QRect(60, 20, 181, 20))
        self.LineEditIP01.setMaxLength(15)
        self.LineEditIP01.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditIP01.setClearButtonEnabled(False)
        self.Label01 = QLabel(self.ModeFrame04)
        self.Label01.setObjectName(u"Label01")
        self.Label01.setGeometry(QRect(20, 20, 40, 20))
        self.Label01.setStyleSheet(u"background-color: #ffffff;")
        self.Label01.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label02 = QLabel(self.ModeFrame04)
        self.Label02.setObjectName(u"Label02")
        self.Label02.setGeometry(QRect(20, 50, 40, 20))
        self.Label02.setStyleSheet(u"background-color: #ffffff;")
        self.Label02.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditMark01 = QLineEdit(self.ModeFrame04)
        self.LineEditMark01.setObjectName(u"LineEditMark01")
        self.LineEditMark01.setGeometry(QRect(60, 50, 51, 20))
        self.LineEditMark01.setMaxLength(2)
        self.LineEditMark01.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditMark01.setClearButtonEnabled(False)
        self.LockCheckBox03 = QCheckBox(self.ModeFrame04)
        self.LockCheckBox03.setObjectName(u"LockCheckBox03")
        self.LockCheckBox03.setGeometry(QRect(190, 50, 51, 21))
        self.LockCheckBox03.setFont(font1)
        self.Label01.raise_()
        self.LineEditIP01.raise_()
        self.Label02.raise_()
        self.LineEditMark01.raise_()
        self.LockCheckBox03.raise_()
        self.Label08 = QLabel(self.Tab01)
        self.Label08.setObjectName(u"Label08")
        self.Label08.setGeometry(QRect(230, 0, 60, 20))
        self.Label08.setStyleSheet(u"background-color: #ffffff;")
        self.Label08.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame05 = QFrame(self.Tab01)
        self.ModeFrame05.setObjectName(u"ModeFrame05")
        self.ModeFrame05.setGeometry(QRect(220, 130, 271, 91))
        self.ModeFrame05.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame05.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditIP02 = QLineEdit(self.ModeFrame05)
        self.LineEditIP02.setObjectName(u"LineEditIP02")
        self.LineEditIP02.setGeometry(QRect(60, 20, 181, 20))
        self.LineEditIP02.setMaxLength(15)
        self.LineEditIP02.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditIP02.setClearButtonEnabled(False)
        self.Label03 = QLabel(self.ModeFrame05)
        self.Label03.setObjectName(u"Label03")
        self.Label03.setGeometry(QRect(20, 20, 40, 20))
        self.Label03.setStyleSheet(u"background-color: #ffffff;")
        self.Label03.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label04 = QLabel(self.ModeFrame05)
        self.Label04.setObjectName(u"Label04")
        self.Label04.setGeometry(QRect(20, 50, 40, 20))
        self.Label04.setStyleSheet(u"background-color: #ffffff;")
        self.Label04.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditMark02 = QLineEdit(self.ModeFrame05)
        self.LineEditMark02.setObjectName(u"LineEditMark02")
        self.LineEditMark02.setGeometry(QRect(60, 50, 51, 20))
        self.LineEditMark02.setMaxLength(2)
        self.LineEditMark02.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditMark02.setClearButtonEnabled(False)
        self.LockCheckBox04 = QCheckBox(self.ModeFrame05)
        self.LockCheckBox04.setObjectName(u"LockCheckBox04")
        self.LockCheckBox04.setGeometry(QRect(190, 50, 51, 21))
        self.LockCheckBox04.setFont(font1)
        self.Label09 = QLabel(self.Tab01)
        self.Label09.setObjectName(u"Label09")
        self.Label09.setGeometry(QRect(230, 120, 60, 20))
        self.Label09.setStyleSheet(u"background-color: #ffffff;")
        self.Label09.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LockAllCheckBox = QCheckBox(self.Tab01)
        self.LockAllCheckBox.setObjectName(u"LockAllCheckBox")
        self.LockAllCheckBox.setGeometry(QRect(410, 240, 81, 21))
        self.LockAllCheckBox.setFont(font1)
        self.Tip03 = QLabel(self.Tab01)
        self.Tip03.setObjectName(u"Tip03")
        self.Tip03.setGeometry(QRect(270, 240, 101, 21))
        font2 = QFont()
        font2.setPointSize(8)
        font2.setUnderline(True)
        self.Tip03.setFont(font2)
        self.Tip03.setOpenExternalLinks(True)
        self.ModeFrame03 = QFrame(self.Tab01)
        self.ModeFrame03.setObjectName(u"ModeFrame03")
        self.ModeFrame03.setGeometry(QRect(10, 170, 191, 91))
        self.ModeFrame03.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ModeFrame03.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame03.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModeFrame03.setLineWidth(1)
        self.ModeFrame03.setMidLineWidth(0)
        self.ExportButton01 = QPushButton(self.ModeFrame03)
        self.ExportButton01.setObjectName(u"ExportButton01")
        self.ExportButton01.setGeometry(QRect(10, 20, 81, 23))
        self.ExportButton02 = QPushButton(self.ModeFrame03)
        self.ExportButton02.setObjectName(u"ExportButton02")
        self.ExportButton02.setGeometry(QRect(10, 50, 81, 23))
        self.ExportButton03 = QPushButton(self.ModeFrame03)
        self.ExportButton03.setObjectName(u"ExportButton03")
        self.ExportButton03.setGeometry(QRect(100, 20, 81, 23))
        self.Label07 = QLabel(self.Tab01)
        self.Label07.setObjectName(u"Label07")
        self.Label07.setGeometry(QRect(20, 160, 35, 20))
        self.Label07.setStyleSheet(u"background-color: #ffffff;")
        self.Label07.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.TabWidget.addTab(self.Tab01, "")
        self.Tab02 = QWidget()
        self.Tab02.setObjectName(u"Tab02")
        self.ModeFrame0201 = QFrame(self.Tab02)
        self.ModeFrame0201.setObjectName(u"ModeFrame0201")
        self.ModeFrame0201.setGeometry(QRect(10, 10, 191, 61))
        self.ModeFrame0201.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ModeFrame0201.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame0201.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModeFrame0201.setLineWidth(1)
        self.ModeFrame0201.setMidLineWidth(0)
        self.LockCheckBox0201 = QCheckBox(self.ModeFrame0201)
        self.LockCheckBox0201.setObjectName(u"LockCheckBox0201")
        self.LockCheckBox0201.setGeometry(QRect(130, 20, 51, 21))
        self.LockCheckBox0201.setFont(font1)
        self.ComboBox0201 = QComboBox(self.ModeFrame0201)
        self.ComboBox0201.addItem("")
        self.ComboBox0201.addItem("")
        self.ComboBox0201.setObjectName(u"ComboBox0201")
        self.ComboBox0201.setGeometry(QRect(20, 20, 101, 22))
        self.Label0201 = QLabel(self.Tab02)
        self.Label0201.setObjectName(u"Label0201")
        self.Label0201.setGeometry(QRect(20, 0, 35, 20))
        self.Label0201.setStyleSheet(u"background-color: #ffffff;")
        self.Label0201.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame0203 = QFrame(self.Tab02)
        self.ModeFrame0203.setObjectName(u"ModeFrame0203")
        self.ModeFrame0203.setGeometry(QRect(220, 10, 271, 61))
        self.ModeFrame0203.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame0203.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditIP0201 = QLineEdit(self.ModeFrame0203)
        self.LineEditIP0201.setObjectName(u"LineEditIP0201")
        self.LineEditIP0201.setGeometry(QRect(80, 20, 111, 20))
        self.LineEditIP0201.setMaxLength(15)
        self.LineEditIP0201.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditIP0201.setClearButtonEnabled(False)
        self.Label0206 = QLabel(self.ModeFrame0203)
        self.Label0206.setObjectName(u"Label0206")
        self.Label0206.setGeometry(QRect(10, 20, 71, 20))
        self.Label0206.setStyleSheet(u"background-color: #ffffff;")
        self.Label0206.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LockCheckBox0203 = QCheckBox(self.ModeFrame0203)
        self.LockCheckBox0203.setObjectName(u"LockCheckBox0203")
        self.LockCheckBox0203.setGeometry(QRect(200, 20, 51, 21))
        self.LockCheckBox0203.setFont(font1)
        self.Label0206.raise_()
        self.LockCheckBox0203.raise_()
        self.LineEditIP0201.raise_()
        self.Label0203 = QLabel(self.Tab02)
        self.Label0203.setObjectName(u"Label0203")
        self.Label0203.setGeometry(QRect(230, 0, 51, 20))
        self.Label0203.setStyleSheet(u"background-color: #ffffff;")
        self.Label0203.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame0204 = QFrame(self.Tab02)
        self.ModeFrame0204.setObjectName(u"ModeFrame0204")
        self.ModeFrame0204.setGeometry(QRect(220, 90, 271, 61))
        self.ModeFrame0204.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame0204.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditIP0202 = QLineEdit(self.ModeFrame0204)
        self.LineEditIP0202.setObjectName(u"LineEditIP0202")
        self.LineEditIP0202.setGeometry(QRect(80, 20, 111, 20))
        self.LineEditIP0202.setMaxLength(15)
        self.LineEditIP0202.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditIP0202.setClearButtonEnabled(False)
        self.Label0207 = QLabel(self.ModeFrame0204)
        self.Label0207.setObjectName(u"Label0207")
        self.Label0207.setGeometry(QRect(10, 20, 71, 20))
        self.Label0207.setStyleSheet(u"background-color: #ffffff;")
        self.Label0207.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LockCheckBox0204 = QCheckBox(self.ModeFrame0204)
        self.LockCheckBox0204.setObjectName(u"LockCheckBox0204")
        self.LockCheckBox0204.setGeometry(QRect(200, 20, 51, 21))
        self.LockCheckBox0204.setFont(font1)
        self.Label0207.raise_()
        self.LockCheckBox0204.raise_()
        self.LineEditIP0202.raise_()
        self.Label0204 = QLabel(self.Tab02)
        self.Label0204.setObjectName(u"Label0204")
        self.Label0204.setGeometry(QRect(230, 80, 51, 20))
        self.Label0204.setStyleSheet(u"background-color: #ffffff;")
        self.Label0204.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame0202 = QFrame(self.Tab02)
        self.ModeFrame0202.setObjectName(u"ModeFrame0202")
        self.ModeFrame0202.setGeometry(QRect(10, 90, 191, 61))
        self.ModeFrame0202.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ModeFrame0202.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame0202.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModeFrame0202.setLineWidth(1)
        self.ModeFrame0202.setMidLineWidth(0)
        self.ComboBox0202 = QComboBox(self.ModeFrame0202)
        self.ComboBox0202.addItem("")
        self.ComboBox0202.addItem("")
        self.ComboBox0202.addItem("")
        self.ComboBox0202.addItem("")
        self.ComboBox0202.addItem("")
        self.ComboBox0202.setObjectName(u"ComboBox0202")
        self.ComboBox0202.setEnabled(True)
        self.ComboBox0202.setGeometry(QRect(20, 20, 101, 22))
        self.LockCheckBox0202 = QCheckBox(self.ModeFrame0202)
        self.LockCheckBox0202.setObjectName(u"LockCheckBox0202")
        self.LockCheckBox0202.setGeometry(QRect(130, 20, 51, 21))
        self.LockCheckBox0202.setFont(font1)
        self.LockCheckBox0202.setChecked(False)
        self.Label0202 = QLabel(self.Tab02)
        self.Label0202.setObjectName(u"Label0202")
        self.Label0202.setGeometry(QRect(20, 80, 35, 20))
        self.Label0202.setStyleSheet(u"background-color: #ffffff;")
        self.Label0202.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModeFrame0205 = QFrame(self.Tab02)
        self.ModeFrame0205.setObjectName(u"ModeFrame0205")
        self.ModeFrame0205.setGeometry(QRect(10, 170, 481, 111))
        self.ModeFrame0205.setFrameShape(QFrame.Shape.Box)
        self.ModeFrame0205.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditSET301 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET301.setObjectName(u"LineEditSET301")
        self.LineEditSET301.setGeometry(QRect(70, 20, 111, 20))
        self.LineEditSET301.setMaxLength(15)
        self.LineEditSET301.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET301.setClearButtonEnabled(False)
        self.LabelSET301 = QLabel(self.ModeFrame0205)
        self.LabelSET301.setObjectName(u"LabelSET301")
        self.LabelSET301.setGeometry(QRect(10, 20, 61, 20))
        self.LabelSET301.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET301.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LockCheckBox0205 = QCheckBox(self.ModeFrame0205)
        self.LockCheckBox0205.setObjectName(u"LockCheckBox0205")
        self.LockCheckBox0205.setGeometry(QRect(410, 80, 51, 21))
        self.LockCheckBox0205.setFont(font1)
        self.LabelSET303 = QLabel(self.ModeFrame0205)
        self.LabelSET303.setObjectName(u"LabelSET303")
        self.LabelSET303.setGeometry(QRect(10, 50, 61, 20))
        self.LabelSET303.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET303.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditSET303 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET303.setObjectName(u"LineEditSET303")
        self.LineEditSET303.setGeometry(QRect(70, 50, 351, 20))
        self.LineEditSET303.setMaxLength(200)
        self.LineEditSET303.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET303.setClearButtonEnabled(False)
        self.LineEditSET302 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET302.setObjectName(u"LineEditSET302")
        self.LineEditSET302.setGeometry(QRect(250, 20, 111, 20))
        self.LineEditSET302.setMaxLength(200)
        self.LineEditSET302.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET302.setClearButtonEnabled(False)
        self.LabelSET302 = QLabel(self.ModeFrame0205)
        self.LabelSET302.setObjectName(u"LabelSET302")
        self.LabelSET302.setGeometry(QRect(190, 20, 61, 20))
        self.LabelSET302.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET302.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LabelSET304 = QLabel(self.ModeFrame0205)
        self.LabelSET304.setObjectName(u"LabelSET304")
        self.LabelSET304.setGeometry(QRect(10, 80, 41, 20))
        self.LabelSET304.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET304.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditSET304 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET304.setObjectName(u"LineEditSET304")
        self.LineEditSET304.setGeometry(QRect(50, 80, 71, 20))
        self.LineEditSET304.setMaxLength(30)
        self.LineEditSET304.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET304.setClearButtonEnabled(False)
        self.LabelSET305 = QLabel(self.ModeFrame0205)
        self.LabelSET305.setObjectName(u"LabelSET305")
        self.LabelSET305.setGeometry(QRect(140, 80, 41, 20))
        self.LabelSET305.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET305.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditSET305 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET305.setObjectName(u"LineEditSET305")
        self.LineEditSET305.setGeometry(QRect(180, 80, 71, 20))
        self.LineEditSET305.setMaxLength(30)
        self.LineEditSET305.setEchoMode(QLineEdit.EchoMode.Password)
        self.LineEditSET305.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET305.setClearButtonEnabled(False)
        self.LabelSET306 = QLabel(self.ModeFrame0205)
        self.LabelSET306.setObjectName(u"LabelSET306")
        self.LabelSET306.setGeometry(QRect(270, 80, 41, 20))
        self.LabelSET306.setStyleSheet(u"background-color: #ffffff;")
        self.LabelSET306.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditSET306 = QLineEdit(self.ModeFrame0205)
        self.LineEditSET306.setObjectName(u"LineEditSET306")
        self.LineEditSET306.setGeometry(QRect(310, 80, 71, 20))
        self.LineEditSET306.setMaxLength(5)
        self.LineEditSET306.setEchoMode(QLineEdit.EchoMode.Normal)
        self.LineEditSET306.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditSET306.setClearButtonEnabled(False)
        self.LockCheckBox0205x2 = QCheckBox(self.ModeFrame0205)
        self.LockCheckBox0205x2.setObjectName(u"LockCheckBox0205x2")
        self.LockCheckBox0205x2.setGeometry(QRect(380, 20, 81, 21))
        self.LockCheckBox0205x2.setFont(font1)
        self.LabelSET301.raise_()
        self.LockCheckBox0205.raise_()
        self.LineEditSET301.raise_()
        self.LabelSET303.raise_()
        self.LineEditSET303.raise_()
        self.LabelSET302.raise_()
        self.LineEditSET302.raise_()
        self.LabelSET304.raise_()
        self.LineEditSET304.raise_()
        self.LabelSET305.raise_()
        self.LineEditSET305.raise_()
        self.LabelSET306.raise_()
        self.LineEditSET306.raise_()
        self.LockCheckBox0205x2.raise_()
        self.Label0205 = QLabel(self.Tab02)
        self.Label0205.setObjectName(u"Label0205")
        self.Label0205.setGeometry(QRect(20, 160, 51, 20))
        self.Label0205.setStyleSheet(u"background-color: #ffffff;")
        self.Label0205.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.TabWidget.addTab(self.Tab02, "")
        self.Tab03 = QWidget()
        self.Tab03.setObjectName(u"Tab03")
        self.InfoFrame0301 = QFrame(self.Tab03)
        self.InfoFrame0301.setObjectName(u"InfoFrame0301")
        self.InfoFrame0301.setGeometry(QRect(10, 10, 201, 191))
        self.InfoFrame0301.setFrameShape(QFrame.Shape.Box)
        self.InfoFrame0301.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditLive01 = QLineEdit(self.InfoFrame0301)
        self.LineEditLive01.setObjectName(u"LineEditLive01")
        self.LineEditLive01.setGeometry(QRect(80, 20, 51, 20))
        self.LineEditLive01.setMaxLength(15)
        self.LineEditLive01.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditLive01.setClearButtonEnabled(False)
        self.Label0304 = QLabel(self.InfoFrame0301)
        self.Label0304.setObjectName(u"Label0304")
        self.Label0304.setGeometry(QRect(10, 20, 71, 20))
        self.Label0304.setStyleSheet(u"background-color: #ffffff;")
        self.Label0304.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label0308 = QLabel(self.InfoFrame0301)
        self.Label0308.setObjectName(u"Label0308")
        self.Label0308.setGeometry(QRect(130, 20, 41, 20))
        self.Label0308.setStyleSheet(u"background-color: #ffffff;")
        self.Label0308.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label0305 = QLabel(self.InfoFrame0301)
        self.Label0305.setObjectName(u"Label0305")
        self.Label0305.setGeometry(QRect(10, 50, 71, 20))
        self.Label0305.setStyleSheet(u"background-color: #ffffff;")
        self.Label0305.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditLive02 = QLineEdit(self.InfoFrame0301)
        self.LineEditLive02.setObjectName(u"LineEditLive02")
        self.LineEditLive02.setGeometry(QRect(80, 50, 51, 20))
        self.LineEditLive02.setMaxLength(15)
        self.LineEditLive02.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditLive02.setClearButtonEnabled(False)
        self.Label0309 = QLabel(self.InfoFrame0301)
        self.Label0309.setObjectName(u"Label0309")
        self.Label0309.setGeometry(QRect(130, 50, 41, 20))
        self.Label0309.setStyleSheet(u"background-color: #ffffff;")
        self.Label0309.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label0306 = QLabel(self.InfoFrame0301)
        self.Label0306.setObjectName(u"Label0306")
        self.Label0306.setGeometry(QRect(10, 80, 71, 20))
        self.Label0306.setStyleSheet(u"background-color: #ffffff;")
        self.Label0306.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditLive03 = QLineEdit(self.InfoFrame0301)
        self.LineEditLive03.setObjectName(u"LineEditLive03")
        self.LineEditLive03.setGeometry(QRect(80, 80, 51, 20))
        self.LineEditLive03.setMaxLength(15)
        self.LineEditLive03.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditLive03.setClearButtonEnabled(False)
        self.Label0310 = QLabel(self.InfoFrame0301)
        self.Label0310.setObjectName(u"Label0310")
        self.Label0310.setGeometry(QRect(130, 80, 31, 20))
        self.Label0310.setStyleSheet(u"background-color: #ffffff;")
        self.Label0310.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LiveButton01 = QPushButton(self.InfoFrame0301)
        self.LiveButton01.setObjectName(u"LiveButton01")
        self.LiveButton01.setGeometry(QRect(100, 150, 75, 23))
        self.Label0307 = QLabel(self.InfoFrame0301)
        self.Label0307.setObjectName(u"Label0307")
        self.Label0307.setGeometry(QRect(10, 110, 71, 20))
        self.Label0307.setStyleSheet(u"background-color: #ffffff;")
        self.Label0307.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LineEditLive04 = QLineEdit(self.InfoFrame0301)
        self.LineEditLive04.setObjectName(u"LineEditLive04")
        self.LineEditLive04.setGeometry(QRect(80, 110, 51, 20))
        self.LineEditLive04.setMaxLength(15)
        self.LineEditLive04.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditLive04.setClearButtonEnabled(False)
        self.Label0311 = QLabel(self.InfoFrame0301)
        self.Label0311.setObjectName(u"Label0311")
        self.Label0311.setGeometry(QRect(130, 110, 51, 20))
        self.Label0311.setStyleSheet(u"background-color: #ffffff;")
        self.Label0311.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label0304.raise_()
        self.Label0308.raise_()
        self.LineEditLive01.raise_()
        self.Label0305.raise_()
        self.Label0309.raise_()
        self.LineEditLive02.raise_()
        self.Label0306.raise_()
        self.Label0310.raise_()
        self.LineEditLive03.raise_()
        self.LiveButton01.raise_()
        self.Label0307.raise_()
        self.Label0311.raise_()
        self.LineEditLive04.raise_()
        self.Label0301 = QLabel(self.Tab03)
        self.Label0301.setObjectName(u"Label0301")
        self.Label0301.setGeometry(QRect(20, 0, 61, 20))
        self.Label0301.setStyleSheet(u"background-color: #ffffff;")
        self.Label0301.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.InfoFrame0302 = QFrame(self.Tab03)
        self.InfoFrame0302.setObjectName(u"InfoFrame0302")
        self.InfoFrame0302.setGeometry(QRect(230, 10, 251, 191))
        self.InfoFrame0302.setFrameShape(QFrame.Shape.Box)
        self.InfoFrame0302.setFrameShadow(QFrame.Shadow.Sunken)
        self.LineEditBit01 = QLineEdit(self.InfoFrame0302)
        self.LineEditBit01.setObjectName(u"LineEditBit01")
        self.LineEditBit01.setGeometry(QRect(30, 20, 31, 20))
        self.LineEditBit01.setMaxLength(15)
        self.LineEditBit01.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditBit01.setClearButtonEnabled(False)
        self.Label0312 = QLabel(self.InfoFrame0302)
        self.Label0312.setObjectName(u"Label0312")
        self.Label0312.setGeometry(QRect(60, 20, 41, 20))
        self.Label0312.setStyleSheet(u"background-color: #ffffff;")
        self.Label0312.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CBitButton01 = QPushButton(self.InfoFrame0302)
        self.CBitButton01.setObjectName(u"CBitButton01")
        self.CBitButton01.setGeometry(QRect(110, 10, 91, 23))
        self.CBitButton02 = QPushButton(self.InfoFrame0302)
        self.CBitButton02.setObjectName(u"CBitButton02")
        self.CBitButton02.setGeometry(QRect(110, 40, 91, 23))
        self.LineEditBit02 = QLineEdit(self.InfoFrame0302)
        self.LineEditBit02.setObjectName(u"LineEditBit02")
        self.LineEditBit02.setGeometry(QRect(20, 90, 41, 20))
        self.LineEditBit02.setMaxLength(15)
        self.LineEditBit02.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.LineEditBit02.setClearButtonEnabled(False)
        self.Label0313 = QLabel(self.InfoFrame0302)
        self.Label0313.setObjectName(u"Label0313")
        self.Label0313.setGeometry(QRect(60, 90, 41, 20))
        self.Label0313.setStyleSheet(u"background-color: #ffffff;")
        self.Label0313.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CBitButton03 = QPushButton(self.InfoFrame0302)
        self.CBitButton03.setObjectName(u"CBitButton03")
        self.CBitButton03.setGeometry(QRect(110, 80, 91, 23))
        self.CBitButton04 = QPushButton(self.InfoFrame0302)
        self.CBitButton04.setObjectName(u"CBitButton04")
        self.CBitButton04.setGeometry(QRect(110, 110, 91, 23))
        self.Tip04 = QLabel(self.InfoFrame0302)
        self.Tip04.setObjectName(u"Tip04")
        self.Tip04.setGeometry(QRect(20, 150, 201, 21))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setUnderline(True)
        self.Tip04.setFont(font3)
        self.Tip04.setOpenExternalLinks(True)
        self.Label0312.raise_()
        self.LineEditBit01.raise_()
        self.CBitButton01.raise_()
        self.CBitButton02.raise_()
        self.Label0313.raise_()
        self.LineEditBit02.raise_()
        self.CBitButton03.raise_()
        self.CBitButton04.raise_()
        self.Tip04.raise_()
        self.InfoFrame0303 = QFrame(self.Tab03)
        self.InfoFrame0303.setObjectName(u"InfoFrame0303")
        self.InfoFrame0303.setGeometry(QRect(10, 220, 471, 61))
        self.InfoFrame0303.setFrameShape(QFrame.Shape.Box)
        self.InfoFrame0303.setFrameShadow(QFrame.Shadow.Sunken)
        self.Tip05 = QLabel(self.InfoFrame0303)
        self.Tip05.setObjectName(u"Tip05")
        self.Tip05.setGeometry(QRect(20, 20, 161, 21))
        self.Tip05.setFont(font3)
        self.Tip05.setOpenExternalLinks(True)
        self.Tip06 = QLabel(self.InfoFrame0303)
        self.Tip06.setObjectName(u"Tip06")
        self.Tip06.setGeometry(QRect(190, 20, 231, 21))
        self.Tip06.setFont(font3)
        self.Tip06.setOpenExternalLinks(True)
        self.Label0303 = QLabel(self.Tab03)
        self.Label0303.setObjectName(u"Label0303")
        self.Label0303.setGeometry(QRect(20, 210, 61, 20))
        self.Label0303.setStyleSheet(u"background-color: #ffffff;")
        self.Label0303.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Label0302 = QLabel(self.Tab03)
        self.Label0302.setObjectName(u"Label0302")
        self.Label0302.setGeometry(QRect(240, 0, 61, 20))
        self.Label0302.setStyleSheet(u"background-color: #ffffff;")
        self.Label0302.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.TabWidget.addTab(self.Tab03, "")
        self.Tab04 = QWidget()
        self.Tab04.setObjectName(u"Tab04")
        self.comboBox0401 = QComboBox(self.Tab04)
        self.comboBox0401.addItem("")
        self.comboBox0401.addItem("")
        self.comboBox0401.addItem("")
        self.comboBox0401.addItem("")
        self.comboBox0401.addItem("")
        self.comboBox0401.setObjectName(u"comboBox0401")
        self.comboBox0401.setGeometry(QRect(20, 10, 71, 22))
        self.textEdit0401 = QTextEdit(self.Tab04)
        self.textEdit0401.setObjectName(u"textEdit0401")
        self.textEdit0401.setGeometry(QRect(20, 140, 461, 141))
        self.label0401 = QLabel(self.Tab04)
        self.label0401.setObjectName(u"label0401")
        self.label0401.setGeometry(QRect(170, 10, 301, 20))
        self.label0401.setStyleSheet(u"color: red")
        self.comboBox0402 = QComboBox(self.Tab04)
        self.comboBox0402.addItem("")
        self.comboBox0402.addItem("")
        self.comboBox0402.setObjectName(u"comboBox0402")
        self.comboBox0402.setGeometry(QRect(100, 10, 61, 22))
        self.textEdit0402 = QTextEdit(self.Tab04)
        self.textEdit0402.setObjectName(u"textEdit0402")
        self.textEdit0402.setGeometry(QRect(20, 40, 461, 91))
        self.TabWidget.addTab(self.Tab04, "")
        self.Tab06 = QWidget()
        self.Tab06.setObjectName(u"Tab06")
        self.lineEdit0601 = QLineEdit(self.Tab06)
        self.lineEdit0601.setObjectName(u"lineEdit0601")
        self.lineEdit0601.setGeometry(QRect(50, 40, 281, 21))
        self.checkBox0601 = QCheckBox(self.Tab06)
        self.checkBox0601.setObjectName(u"checkBox0601")
        self.checkBox0601.setGeometry(QRect(340, 40, 71, 21))
        self.label_600 = QLabel(self.Tab06)
        self.label_600.setObjectName(u"label_600")
        self.label_600.setGeometry(QRect(10, 40, 41, 20))
        self.label_600.setStyleSheet(u"background-color: #ffffff;")
        self.label_600.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.textEdit0601 = QTextEdit(self.Tab06)
        self.textEdit0601.setObjectName(u"textEdit0601")
        self.textEdit0601.setGeometry(QRect(10, 70, 481, 181))
        self.label_601 = QLabel(self.Tab06)
        self.label_601.setObjectName(u"label_601")
        self.label_601.setGeometry(QRect(10, 260, 411, 20))
        self.label_601.setStyleSheet(u"color: red")
        self.label_603 = QLabel(self.Tab06)
        self.label_603.setObjectName(u"label_603")
        self.label_603.setGeometry(QRect(10, 10, 41, 20))
        self.label_603.setStyleSheet(u"background-color: #ffffff;")
        self.label_603.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit0602 = QLineEdit(self.Tab06)
        self.lineEdit0602.setObjectName(u"lineEdit0602")
        self.lineEdit0602.setGeometry(QRect(50, 10, 101, 21))
        self.pushButton0601 = QPushButton(self.Tab06)
        self.pushButton0601.setObjectName(u"pushButton0601")
        self.pushButton0601.setGeometry(QRect(420, 10, 75, 21))
        self.pushButton0601.setCheckable(True)
        self.label_604 = QLabel(self.Tab06)
        self.label_604.setObjectName(u"label_604")
        self.label_604.setGeometry(QRect(200, 10, 41, 20))
        self.label_604.setStyleSheet(u"background-color: #ffffff;")
        self.label_604.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit0603 = QLineEdit(self.Tab06)
        self.lineEdit0603.setObjectName(u"lineEdit0603")
        self.lineEdit0603.setGeometry(QRect(240, 10, 61, 21))
        self.label_605 = QLabel(self.Tab06)
        self.label_605.setObjectName(u"label_605")
        self.label_605.setGeometry(QRect(310, 10, 41, 20))
        self.label_605.setStyleSheet(u"background-color: #ffffff;")
        self.label_605.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit0604 = QLineEdit(self.Tab06)
        self.lineEdit0604.setObjectName(u"lineEdit0604")
        self.lineEdit0604.setGeometry(QRect(350, 10, 61, 21))
        self.lineEdit0604.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit0605 = QLineEdit(self.Tab06)
        self.lineEdit0605.setObjectName(u"lineEdit0605")
        self.lineEdit0605.setGeometry(QRect(150, 10, 41, 21))
        self.pushButton0603 = QPushButton(self.Tab06)
        self.pushButton0603.setObjectName(u"pushButton0603")
        self.pushButton0603.setGeometry(QRect(420, 260, 75, 23))
        self.pushButton0602 = QPushButton(self.Tab06)
        self.pushButton0602.setObjectName(u"pushButton0602")
        self.pushButton0602.setGeometry(QRect(420, 40, 75, 21))
        self.pushButton0602.setCheckable(False)
        self.TabWidget.addTab(self.Tab06, "")
        self.checkBox0601.raise_()
        self.label_600.raise_()
        self.lineEdit0601.raise_()
        self.textEdit0601.raise_()
        self.label_601.raise_()
        self.label_603.raise_()
        self.lineEdit0602.raise_()
        self.pushButton0601.raise_()
        self.label_604.raise_()
        self.lineEdit0603.raise_()
        self.label_605.raise_()
        self.lineEdit0604.raise_()
        self.lineEdit0605.raise_()
        self.pushButton0603.raise_()
        self.pushButton0602.raise_()
        self.Tab05 = QWidget()
        self.Tab05.setObjectName(u"Tab05")
        self.label_1 = QLabel(self.Tab05)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(250, 90, 161, 16))
        self.label_2 = QLabel(self.Tab05)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(250, 150, 71, 16))
        self.label_3 = QLabel(self.Tab05)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 110, 191, 16))
        self.label_4 = QLabel(self.Tab05)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(250, 170, 111, 16))
        self.label_5 = QLabel(self.Tab05)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(250, 130, 181, 16))
        self.label_pic = QLabel(self.Tab05)
        self.label_pic.setObjectName(u"label_pic")
        self.label_pic.setGeometry(QRect(20, 40, 211, 201))
        self.label_pic.setTextFormat(Qt.TextFormat.AutoText)
        self.label_pic.setPixmap(QPixmap(u":/logo/resources/toolboxs.ico"))
        self.label_pic.setScaledContents(True)
        self.TabWidget.addTab(self.Tab05, "")

        self.Right.addWidget(self.TabWidget)

        self.MessageBrowser = QTextBrowser(self.QMainWidget)
        self.MessageBrowser.setObjectName(u"MessageBrowser")
        self.MessageBrowser.setMinimumSize(QSize(510, 300))
        self.MessageBrowser.setMaximumSize(QSize(510, 16777215))
        self.MessageBrowser.setStyleSheet(u"QTextEdit { background-color: #f9f9f9; border: unset; }")
        self.MessageBrowser.setOpenExternalLinks(True)
        self.MessageBrowser.setOpenLinks(True)

        self.Right.addWidget(self.MessageBrowser)

        self.BottomButtonLayout = QHBoxLayout()
        self.BottomButtonLayout.setObjectName(u"BottomButtonLayout")
        self.BottomSpacer01 = QSpacerItem(30, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.BottomButtonLayout.addItem(self.BottomSpacer01)

        self.StartButton = QPushButton(self.QMainWidget)
        self.StartButton.setObjectName(u"StartButton")
        self.StartButton.setMinimumSize(QSize(87, 23))
        self.StartButton.setMaximumSize(QSize(87, 23))
        self.StartButton.setCheckable(True)

        self.BottomButtonLayout.addWidget(self.StartButton)

        self.BottomSpacer02 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.BottomButtonLayout.addItem(self.BottomSpacer02)

        self.ProgressBar = QProgressBar(self.QMainWidget)
        self.ProgressBar.setObjectName(u"ProgressBar")
        self.ProgressBar.setEnabled(True)
        self.ProgressBar.setMinimumSize(QSize(220, 23))
        self.ProgressBar.setMaximumSize(QSize(220, 23))
        self.ProgressBar.setValue(50)

        self.BottomButtonLayout.addWidget(self.ProgressBar)

        self.BottomSpacer03 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.BottomButtonLayout.addItem(self.BottomSpacer03)

        self.ExitButton = QPushButton(self.QMainWidget)
        self.ExitButton.setObjectName(u"ExitButton")
        self.ExitButton.setMinimumSize(QSize(87, 23))
        self.ExitButton.setMaximumSize(QSize(87, 23))

        self.BottomButtonLayout.addWidget(self.ExitButton)

        self.BottomSpacer04 = QSpacerItem(30, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.BottomButtonLayout.addItem(self.BottomSpacer04)


        self.Right.addLayout(self.BottomButtonLayout)


        self.horizontalLayout.addLayout(self.Right)

        QMainWindow.setCentralWidget(self.QMainWidget)

        self.retranslateUi(QMainWindow)

        self.TabWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(QMainWindow)
    # setupUi

    def retranslateUi(self, QMainWindow):
        QMainWindow.setWindowTitle(QCoreApplication.translate("QMainWindow", u"My Tools Box", None))
        self.OpenLabel.setText(QCoreApplication.translate("QMainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
        self.CleanLabel.setText(QCoreApplication.translate("QMainWindow", u"\u6e05\u7a7a\u5217\u8868", None))
        self.ShowLabel.setText(QCoreApplication.translate("QMainWindow", u"\u4fdd\u5b58\u5217\u8868", None))
        self.RegisterLabel.setText(QCoreApplication.translate("QMainWindow", u"\u7a0b\u5e8f\u6ce8\u518c", None))
        self.LogoutLabel.setText(QCoreApplication.translate("QMainWindow", u"\u7a0b\u5e8f\u6ce8\u9500", None))
        self.ListBrowser.setHtml(QCoreApplication.translate("QMainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.LockCheckBox01.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.ComboBox01.setItemText(0, QCoreApplication.translate("QMainWindow", u"HTTP Api", None))
        self.ComboBox01.setItemText(1, QCoreApplication.translate("QMainWindow", u"HTTP Header", None))

        self.Label05.setText(QCoreApplication.translate("QMainWindow", u"\u6a21\u5f0f", None))
        self.LockCheckBox02.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.ComboBox02.setItemText(0, QCoreApplication.translate("QMainWindow", u"A Like", None))
        self.ComboBox02.setItemText(1, QCoreApplication.translate("QMainWindow", u"B Like", None))

        self.Label06.setText(QCoreApplication.translate("QMainWindow", u"\u578b\u53f7", None))
        self.LineEditIP01.setText(QCoreApplication.translate("QMainWindow", u"192.168.1.0", None))
        self.Label01.setText(QCoreApplication.translate("QMainWindow", u"IP \u6bb5\uff1a", None))
        self.Label02.setText(QCoreApplication.translate("QMainWindow", u"\u63a9 \u7801\uff1a", None))
        self.LineEditMark01.setText(QCoreApplication.translate("QMainWindow", u"24", None))
        self.LockCheckBox03.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.Label08.setText(QCoreApplication.translate("QMainWindow", u"\u641c\u7d22\u53c2\u6570", None))
        self.LineEditIP02.setText(QCoreApplication.translate("QMainWindow", u"192.168.2.0", None))
        self.Label03.setText(QCoreApplication.translate("QMainWindow", u"IP \u6bb5\uff1a", None))
        self.Label04.setText(QCoreApplication.translate("QMainWindow", u"\u63a9 \u7801\uff1a", None))
        self.LineEditMark02.setText(QCoreApplication.translate("QMainWindow", u"24", None))
        self.LockCheckBox04.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.Label09.setText(QCoreApplication.translate("QMainWindow", u"\u641c\u7d22\u53c2\u6570", None))
        self.LockAllCheckBox.setText(QCoreApplication.translate("QMainWindow", u"\u5168\u90e8\u9501\u5b9a", None))
        self.Tip03.setText(QCoreApplication.translate("QMainWindow", u"<a style='color: #0066cc' href=\"https://doc.qt.io/qtforpython-6/\">Power By PySide6</a>", None))
        self.ExportButton01.setText(QCoreApplication.translate("QMainWindow", u"\u5bfc\u51fa\u4e3a TXT", None))
        self.ExportButton02.setText(QCoreApplication.translate("QMainWindow", u"\u5bfc\u51fa\u4e3a CSV", None))
        self.ExportButton03.setText(QCoreApplication.translate("QMainWindow", u"\u590d\u5236\u5230\u5217\u8868", None))
        self.Label07.setText(QCoreApplication.translate("QMainWindow", u"\u7ed3\u679c", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab01), QCoreApplication.translate("QMainWindow", u"\u641c\u7d22", None))
        self.LockCheckBox0201.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.ComboBox0201.setItemText(0, QCoreApplication.translate("QMainWindow", u"A Like", None))
        self.ComboBox0201.setItemText(1, QCoreApplication.translate("QMainWindow", u"B Like", None))

        self.Label0201.setText(QCoreApplication.translate("QMainWindow", u"\u578b\u53f7", None))
        self.LineEditIP0201.setText(QCoreApplication.translate("QMainWindow", u"192.168.1.0", None))
        self.Label0206.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u5730\u5740\uff1a", None))
        self.LockCheckBox0203.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.Label0203.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u4e00", None))
        self.LineEditIP0202.setText(QCoreApplication.translate("QMainWindow", u"192.168.1.0", None))
        self.Label0207.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u5730\u5740\uff1a", None))
        self.LockCheckBox0204.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.Label0204.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u4e8c", None))
        self.ComboBox0202.setItemText(0, QCoreApplication.translate("QMainWindow", u"Function 1", None))
        self.ComboBox0202.setItemText(1, QCoreApplication.translate("QMainWindow", u"Function 2", None))
        self.ComboBox0202.setItemText(2, QCoreApplication.translate("QMainWindow", u"Function 3", None))
        self.ComboBox0202.setItemText(3, QCoreApplication.translate("QMainWindow", u"Function 4", None))
        self.ComboBox0202.setItemText(4, QCoreApplication.translate("QMainWindow", u"Function 5", None))

        self.LockCheckBox0202.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.Label0202.setText(QCoreApplication.translate("QMainWindow", u"\u5176\u4ed6", None))
        self.LineEditSET301.setText(QCoreApplication.translate("QMainWindow", u"192.168.1.0", None))
        self.LabelSET301.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u5730\u5740\uff1a", None))
        self.LockCheckBox0205.setText(QCoreApplication.translate("QMainWindow", u"\u9501\u5b9a", None))
        self.LabelSET303.setText(QCoreApplication.translate("QMainWindow", u"\u56de\u8c03\u63a5\u53e3\uff1a", None))
        self.LineEditSET303.setText("")
        self.LineEditSET302.setText("")
        self.LabelSET302.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u53c2\u6570\uff1a", None))
        self.LabelSET304.setText(QCoreApplication.translate("QMainWindow", u"\u8d26\u53f7\uff1a", None))
        self.LineEditSET304.setText("")
        self.LabelSET305.setText(QCoreApplication.translate("QMainWindow", u"\u5bc6\u7801\uff1a", None))
        self.LineEditSET305.setText("")
        self.LabelSET306.setText(QCoreApplication.translate("QMainWindow", u"\u7aef\u53e3\uff1a", None))
        self.LineEditSET306.setText("")
        self.LockCheckBox0205x2.setText(QCoreApplication.translate("QMainWindow", u"\u4f7f\u7528UUID", None))
        self.Label0205.setText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u7f6e\u4e09", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab02), QCoreApplication.translate("QMainWindow", u"\u6279\u91cf\u63a7\u5236", None))
        self.LineEditLive01.setText(QCoreApplication.translate("QMainWindow", u"2048", None))
        self.Label0304.setText(QCoreApplication.translate("QMainWindow", u"\u76f4\u64ad\u7801\u7387\uff1a", None))
        self.Label0308.setText(QCoreApplication.translate("QMainWindow", u"Kbps", None))
        self.Label0305.setText(QCoreApplication.translate("QMainWindow", u"\u76f4\u64ad\u65f6\u957f\uff1a", None))
        self.LineEditLive02.setText(QCoreApplication.translate("QMainWindow", u"60", None))
        self.Label0309.setText(QCoreApplication.translate("QMainWindow", u"\u5206\u949f", None))
        self.Label0306.setText(QCoreApplication.translate("QMainWindow", u"\u9884\u8ba1\u4eba\u6570\uff1a", None))
        self.LineEditLive03.setText(QCoreApplication.translate("QMainWindow", u"60", None))
        self.Label0310.setText(QCoreApplication.translate("QMainWindow", u"\u4eba", None))
        self.LiveButton01.setText(QCoreApplication.translate("QMainWindow", u"\u5f00\u59cb\u8ba1\u7b97", None))
        self.Label0307.setText(QCoreApplication.translate("QMainWindow", u"\u6d41\u91cf\u8d39\u7528\uff1a", None))
        self.LineEditLive04.setText(QCoreApplication.translate("QMainWindow", u"0.26", None))
        self.Label0311.setText(QCoreApplication.translate("QMainWindow", u"\u5143/GB", None))
        self.Label0301.setText(QCoreApplication.translate("QMainWindow", u"\u76f4\u64ad\u8ba1\u7b97", None))
        self.LineEditBit01.setText(QCoreApplication.translate("QMainWindow", u"2", None))
        self.Label0312.setText(QCoreApplication.translate("QMainWindow", u"MB/s", None))
        self.CBitButton01.setText(QCoreApplication.translate("QMainWindow", u"\u8f6c\u6362\u4e3a Mbps", None))
        self.CBitButton02.setText(QCoreApplication.translate("QMainWindow", u"\u8f6c\u6362\u4e3a Kbps", None))
        self.LineEditBit02.setText(QCoreApplication.translate("QMainWindow", u"1000", None))
        self.Label0313.setText(QCoreApplication.translate("QMainWindow", u"Mbps", None))
        self.CBitButton03.setText(QCoreApplication.translate("QMainWindow", u"\u8f6c\u6362\u4e3a MB/s", None))
        self.CBitButton04.setText(QCoreApplication.translate("QMainWindow", u"\u8f6c\u6362\u4e3a Kbps", None))
        self.Tip04.setText(QCoreApplication.translate("QMainWindow", u"<a style='color: #0066cc' href=\"https://purecalculators.com/zh-CN\">\u66f4\u591a\u8bf7\u8bbf\u95ee Pure Calculators \u4f7f\u7528</a>", None))
        self.Tip05.setText(QCoreApplication.translate("QMainWindow", u"<a style='color: #0066cc' href=\"https://cloud.tencent.com/document/product/267/34175\">\u817e\u8baf\u4e91-\u6807\u51c6\u76f4\u64ad\u670d\u52a1\u8d39\u7528</a>", None))
        self.Tip06.setText(QCoreApplication.translate("QMainWindow", u"<a style='color: #0066cc' href=\"https://support.huaweicloud.com/live_faq/live_08_0106.html\">\u534e\u4e3a\u4e91-\u5982\u4f55\u4f30\u7b97\u89c6\u9891\u76f4\u64ad\u7684\u6d41\u91cf\u6d88\u8017\uff1f</a>", None))
        self.Label0303.setText(QCoreApplication.translate("QMainWindow", u"\u53c2\u8003\u6587\u4ef6", None))
        self.Label0302.setText(QCoreApplication.translate("QMainWindow", u"\u7801\u7387\u8f6c\u6362", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab03), QCoreApplication.translate("QMainWindow", u"\u8ba1\u7b97\u5668", None))
        self.comboBox0401.setItemText(0, QCoreApplication.translate("QMainWindow", u"GET", None))
        self.comboBox0401.setItemText(1, QCoreApplication.translate("QMainWindow", u"POST", None))
        self.comboBox0401.setItemText(2, QCoreApplication.translate("QMainWindow", u"PUT", None))
        self.comboBox0401.setItemText(3, QCoreApplication.translate("QMainWindow", u"DELETE", None))
        self.comboBox0401.setItemText(4, QCoreApplication.translate("QMainWindow", u"HEAD", None))

        self.textEdit0401.setHtml(QCoreApplication.translate("QMainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit0401.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u8bf7\u6c42\u53c2\u6570", None))
        self.label0401.setText(QCoreApplication.translate("QMainWindow", u"\u8b66\u544a\uff0c\u53ea\u9700\u586b\u5199\u63a5\u53e3\u8def\u7531\uff0cURL \u4f1a\u81ea\u52a8\u4ece\u5de6\u8fb9\u5217\u8868\u83b7\u53d6", None))
        self.comboBox0402.setItemText(0, QCoreApplication.translate("QMainWindow", u"A Like", None))
        self.comboBox0402.setItemText(1, QCoreApplication.translate("QMainWindow", u"B Like", None))

        self.textEdit0402.setMarkdown("")
        self.textEdit0402.setHtml(QCoreApplication.translate("QMainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit0402.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u63a5\u53e3\u5730\u5740  ", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab04), QCoreApplication.translate("QMainWindow", u"\u8bf7\u6c42\u53d1\u9001", None))
        self.lineEdit0601.setText("")
        self.lineEdit0601.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"control/", None))
        self.checkBox0601.setText(QCoreApplication.translate("QMainWindow", u"\u5355\u53f0\u6d4b\u8bd5", None))
        self.label_600.setText(QCoreApplication.translate("QMainWindow", u"\u4e3b\u9898\uff1a", None))
        self.textEdit0601.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u8bbe\u5907\u63a7\u5236\u4fe1\u606f", None))
        self.label_601.setText(QCoreApplication.translate("QMainWindow", u"\u8b66\u544a\uff0c\u8bf7\u4f7f\u7528\u4e13\u95e8\u6a21\u677f\u5bfc\u5165\u8bbe\u5907\uff0c\u540c\u65f6\u5355\u53f0\u6d4b\u8bd5\u65f6\u8bf7\u5728\u4e3b\u9898\u5199\u5165\u5bf9\u5e94\u8bbe\u5907 ID", None))
        self.label_603.setText(QCoreApplication.translate("QMainWindow", u"\u5e73\u53f0\uff1a", None))
        self.lineEdit0602.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"MQTT \u5730\u5740", None))
        self.pushButton0601.setText(QCoreApplication.translate("QMainWindow", u"\u8fde\u63a5", None))
        self.label_604.setText(QCoreApplication.translate("QMainWindow", u"\u8d26\u53f7\uff1a", None))
        self.lineEdit0603.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u8d26\u53f7", None))
        self.label_605.setText(QCoreApplication.translate("QMainWindow", u"\u5bc6\u7801\uff1a", None))
        self.lineEdit0604.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u5bc6\u7801", None))
        self.lineEdit0605.setText(QCoreApplication.translate("QMainWindow", u"1883", None))
        self.lineEdit0605.setPlaceholderText(QCoreApplication.translate("QMainWindow", u"\u7aef\u53e3", None))
        self.pushButton0603.setText(QCoreApplication.translate("QMainWindow", u"\u6a21\u677f\u4e0b\u8f7d", None))
        self.pushButton0602.setText(QCoreApplication.translate("QMainWindow", u"\u8ba2\u9605", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab06), QCoreApplication.translate("QMainWindow", u"MQTT", None))
        self.label_1.setText(QCoreApplication.translate("QMainWindow", u"My Tools Box \u5de5\u5177\u7bb1", None))
        self.label_2.setText(QCoreApplication.translate("QMainWindow", u"Version: 1.2", None))
        self.label_3.setText(QCoreApplication.translate("QMainWindow", u"Copyright (C) by LiangMingJian", None))
        self.label_4.setText(QCoreApplication.translate("QMainWindow", u"Time: 2026/01/05", None))
        self.label_5.setText(QCoreApplication.translate("QMainWindow", u"Company: None", None))
        self.label_pic.setText("")
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Tab05), QCoreApplication.translate("QMainWindow", u"\u7248\u672c\u4fe1\u606f", None))
        self.StartButton.setText(QCoreApplication.translate("QMainWindow", u"Start", None))
        self.ExitButton.setText(QCoreApplication.translate("QMainWindow", u"Exit", None))
    # retranslateUi

